version: '3.8'

services:
  # ==========================================
  # 1. ECOSISTEMA NESTJS (API DE COTIZACIONES)
  # ==========================================
  db-master:
    build:
      context: ./alflab-cotizaciones-api
      dockerfile: Dockerfile.db
    container_name: alflab_db_master
    restart: always
    env_file:             
      - .env
    command: --server-id=1 --log-bin=mysql-bin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MASTER_ROOT_PASSWORD:-Root_Profe_2026}
      MYSQL_DATABASE: ${DB_MASTER_DATABASE:-alflab_cotizaciones}
    ports:
      - "3309:3306"
    volumes:
      # 👇 VOLUMEN PERSISTENTE: Se creará una carpeta "data" en tu proyecto
      - ./data/mysql_master:/var/lib/mysql

  db-replica:
    image: mysql:8.0
    container_name: alflab_db_replica
    restart: always
    env_file:             
      - .env
    command: --server-id=2 --read-only=1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-Root_Profe_2026}
      MYSQL_DATABASE: ${DB_REPLICA_DATABASE:-alflab_cotizaciones_replica}
    ports:
      - "3307:3306"
    volumes:
      # 👇 VOLUMEN PERSISTENTE
      - ./data/mysql_replica:/var/lib/mysql

  api-cotizaciones:
    build:
      context: ./alflab-cotizaciones-api
      dockerfile: Dockerfile
    container_name: alflab_api_node
    restart: always
    env_file:             
      - .env
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db-master
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_MASTER_ROOT_PASSWORD:-Root_Profe_2026}
      - DB_NAME=${DB_MASTER_DATABASE:-alflab_cotizaciones}
      - JWT_SECRET=${JWT_SECRET:-Firma_Local_De_Prueba_2026}
      - TZ=America/Mexico_City
    depends_on:
      - db-master

  # ==========================================
  # 2. ECOSISTEMA .NET (SISTEMA PRINCIPAL)
  # ==========================================
  db-alflab-dotnet:
    image: mysql:8.0
    container_name: alflab_db_dotnet
    restart: always
    env_file:             
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: alflab_principal
    ports:
      - "3308:3306"
    volumes:
      # 👇 VOLUMEN PERSISTENTE
      - ./data/mysql_dotnet:/var/lib/mysql

  api-principal:
    build:
      context: ./AlfLab.Api 
      dockerfile: Dockerfile
    container_name: alflab_api_dotnet
    restart: always
    env_file:             
      - .env
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db-alflab-dotnet;Database=alflab_principal;Uid=root;Pwd=${DB_PASSWORD:-SuperPasswordPro_2026};
      - JWT_SECRET=${JWT_SECRET:-EstaEsUnaLlaveDeRespaldoPorSiFallaElEnv123!}
    depends_on:
      - db-alflab-dotnet
      - db-replica

# 🔴 ELIMINAMOS LA SECCIÓN "volumes:" DE AQUÍ ABAJO PORQUE AHORA USAMOS CARPETAS REALES