@HostAddress = http://localhost:5000
### =========================================================
### PASO 0: CREAR EL USUARIO ADMINISTRADOR
### =========================================================
POST {{HostAddress}}/api/auth/registrar
Content-Type: application/json

{
  "nombreCompleto": "Admin AlfLab",
  "correo": "admin1@alflab.com",
  "password": "TuPasswordReal123!",
  "rol": "Admin"
}

### ====================================================================
### 🟢 FASE 1: PREPARACIÓN Y OBTENCIÓN DE TOKENS (LOGINS)
### Objetivo: Iniciar sesión para guardar automáticamente los tokens en memoria.
### ====================================================================

# @name loginAdmin
# 1.A - LOGIN ADMINISTRADOR (Ejecuta esto primero)
POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "correo": "admin1@alflab.com",
  "password": "TuPasswordReal123!" 
}

###
@tokenAdmin = {{loginAdmin.response.body.token}}

# @name loginVentas
# 1.B - LOGIN VENTAS (Ejecuta esto para tener un token de bajo nivel)
POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "correo": "ventas@alflab.com",
  "password": "PasswordSeguro123!"
}

###
@tokenVentas = {{loginVentas.response.body.token}}


### ====================================================================
### 🔵 FASE 2: PRUEBAS DE FUNCIONAMIENTO NORMAL (RBAC)
### Objetivo: Validar que el sistema hace lo que debe hacer con permisos correctos.
### ====================================================================

# 2.A - REGISTRO EXITOSO (Usa token de Admin, debe dar 200 OK)
POST {{HostAddress}}/api/auth/registrar
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "nombreCompleto": "Nuevo Empleado",
  "correo": "ventas1@alflab.com",
  "password": "PasswordSeguro123!"
}

###

# 2.B - ACCESO DENEGADO POR FALTA DE RANGOS (Usa token de Ventas, debe dar 403 Forbidden)
# Un empleado de Ventas intenta registrar a alguien, pero no tiene el Rol Admin
POST {{HostAddress}}/api/auth/registrar
Authorization: Bearer {{tokenVentas}}
Content-Type: application/json

{
  "nombreCompleto": "Amigo del de Ventas",
  "correo": "amigo@alflab.com",
  "password": "PasswordSeguro123!"
}


### ====================================================================
### 🔴 FASE 3: PRUEBAS DE ATAQUE Y CIBERSEGURIDAD (HACKEO SIMULADO)
### Objetivo: Validar los escudos de defensa de tu API de .NET.
### ====================================================================

# 🛡️ DEFENSA 1: PROTECCIÓN CONTRA ANÓNIMOS (Debe dar 401 Unauthorized)
# Un intruso sin token intenta registrar un usuario.
POST {{HostAddress}}/api/auth/registrar
Content-Type: application/json

{
  "nombreCompleto": "Intruso Anónimo",
  "correo": "intruso@alflab.com",
  "password": "HackerPassword123"
}

###

# 🛡️ DEFENSA 2: SUPLANTACIÓN DE CREDENCIALES / SPOOFING (Debe dar 401 Unauthorized)
# Un atacante toma el token válido de Ventas e intenta inyectarle código para alterar la firma matemática y ganar privilegios.
POST {{HostAddress}}/api/auth/registrar
Authorization: Bearer {{tokenVentas}}ESTO_ES_UN_INJECT_MALICIOSO_ALTERANDO_LA_FIRMA
Content-Type: application/json

{
  "nombreCompleto": "Hacker Infiltrado",
  "correo": "hacker2@alflab.com",
  "password": "HackerPassword123!"
}

###

# 🛡️ DEFENSA 3: INYECCIÓN DE CÓDIGO XSS (Debe dar 400 Bad Request y guardar auditoría)
# Un Admin comprometido intenta registrar a alguien con un script malicioso en el nombre para atacar el Frontend.
POST {{HostAddress}}/api/auth/registrar
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "nombreCompleto": "<script>alert('Robando cookies');</script> Juan",
  "correo": "xss@alflab.com",
  "password": "Password123!"
}

###

# 🛡️ DEFENSA 4: ATAQUE DE FUERZA BRUTA (Debe dar error por intentos excedidos)
# Dispara este bloque rápido 4 o 5 veces seguidas.
POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "correo": "admin1@alflab.com",
  "password": "ClaveIncorrecta123"
}