name: AlfLab Main Pipeline

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

# 🌐 VARIABLES GLOBALES (Leídas desde la interfaz de GitHub)
env:
  APP_NAME: ${{ vars.APP_NAME }}
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
  # =========================================================
  # 📦 FASE 3: ASOCIACIÓN DEL CONTENEDOR 1 (NestJS)
  # =========================================================
  api-cotizaciones-nestjs:
    uses: ./.github/workflows/reusable-build.yml 
    with:
      service_name: "AlfLab-Cotizaciones-NestJS"
      dockerfile_path: "./alflab-cotizaciones-api/Dockerfile"
      context_path: "./alflab-cotizaciones-api"
    secrets: inherit # 👈 CLAVE DE SEGURIDAD: Hereda los Action Secrets al molde

  # =========================================================
  # 📦 FASE 3: ASOCIACIÓN DEL CONTENEDOR 2 (.NET)
  # =========================================================
  api-principal-dotnet:
    uses: ./.github/workflows/reusable-build.yml 
    with:
      service_name: "AlfLab-Principal-DotNet"
      dockerfile_path: "./AlfLab.Api/Dockerfile" # (Ajustado a tu estructura real)
      context_path: "./AlfLab.Api"
    secrets: inherit # 👈 CLAVE DE SEGURIDAD: Hereda los Action Secrets al molde