name: Reusable Build Framework

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
        description: "Nombre del microservicio"
      dockerfile_path:
        required: true
        type: string
        description: "Ruta relativa hacia el Dockerfile"
      context_path:
        required: true
        type: string
        description: "Contexto de ejecución para el comando Docker Build"

jobs:
  build-process:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      # El paso original que tú armaste para las variables de entrada
      - name: 📢 Log Variable Configuration
        run: |
          echo "==== CONFIGURACIÓN DE VARIABLES DETECTADA ===="
          echo "Servicio a procesar: ${{ inputs.service_name }}"
          echo "Ubicación del Dockerfile: ${{ inputs.dockerfile_path }}"
          echo "Contexto de Docker: ${{ inputs.context_path }}"

      # El paso extra para impresionar al maestro con DevSecOps
      - name: 🔐 Verificar Inyección de Secretos
        run: |
          echo "Verificando disponibilidad de secretos en el entorno aislado..."
          if [ -n "${{ secrets.DB_PASSWORD }}" ]; then
            echo "✅ Secretos críticos cargados en memoria y listos para Docker."
          else
            echo "❌ Alerta: Los secretos no se heredaron correctamente."
            exit 1
          fi

      # =========================================================
      # 📝 MANIPULACIÓN DINÁMICA DE APPSETTINGS (Requisito de clase)
      # =========================================================
      - name: ⚙️ Reemplazar appsettings (Solo para proyectos .NET)
        shell: pwsh
        run: |
          # 1. Usamos la variable de entrada para buscar en la carpeta correcta
          $rutaJson = "${{ inputs.context_path }}/appsettings.json"
          
          # 2. Verificamos si el archivo existe antes de intentar abrirlo
          if (Test-Path $rutaJson) {
              echo "🔄 Archivo appsettings.json detectado. Inyectando secretos..."
              
              # Leer y convertir el JSON
              $json = Get-Content $rutaJson | ConvertFrom-Json
              
              # Reemplazar la cadena de conexión usando el secreto heredado
              $json.ConnectionStrings.DefaultConnection = "Server=db-alflab-dotnet;Database=alflab_principal;Uid=root;Pwd=${{ secrets.DB_PASSWORD }};"
              
              # Guardar los cambios sobrescribiendo el archivo
              $json | ConvertTo-Json -Depth 10 | Set-Content $rutaJson
              
              echo "✅ Variables de entorno inyectadas correctamente en el JSON."
          } else {
              echo "⏭️ No es un proyecto .NET (o no hay appsettings.json). Omitiendo este paso."
          }