name: Reusable Build Framework

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
        description: "Nombre del microservicio"
      dockerfile_path:
        required: true
        type: string
        description: "Ruta relativa hacia el Dockerfile"
      context_path:
        required: true
        type: string
        description: "Contexto de ejecucion para el comando Docker Build"

jobs:
  build-process:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log Variable Configuration
        run: |
          echo "Configuracion de variables detectada"
          echo "Servicio a procesar: ${{ inputs.service_name }}"
          echo "Ubicacion del Dockerfile: ${{ inputs.dockerfile_path }}"
          echo "Contexto de Docker: ${{ inputs.context_path }}"

      - name: Imprimir Variables del Repositorio
        run: |
          echo "Variables globales de GitHub:"
          echo "Host de Base de Datos: ${{ vars.DB_HOST }}"
          echo "Puerto de la API: ${{ vars.PORT_API }}"
          echo "Base de Datos Master: ${{ vars.DB_MASTER_DATABASE }}"

      - name: Verificar Inyeccion de Secretos
        run: |
          echo "Verificando disponibilidad de secretos en el entorno aislado..."
          if [ -n "${{ secrets.DB_PASSWORD }}" ]; then
            echo "Secretos criticos cargados en memoria y listos para Docker."
          else
            echo "Alerta: Los secretos no se heredaron correctamente."
            exit 1
          fi

      - name: Reemplazar appsettings para proyectos .NET
        shell: pwsh
        run: |
          $rutaJson = "${{ inputs.context_path }}/appsettings.json"
          
          if (Test-Path $rutaJson) {
              echo "Archivo appsettings.json detectado. Inyectando secretos..."
              $json = Get-Content $rutaJson | ConvertFrom-Json
              $json.ConnectionStrings.DefaultConnection = "Server=db-alflab-dotnet;Database=alflab_principal;Uid=root;Pwd=${{ secrets.DB_PASSWORD }};"
              $json | ConvertTo-Json -Depth 10 | Set-Content $rutaJson
              echo "Variables de entorno inyectadas correctamente en el JSON."
          } else {
              echo "No es un proyecto .NET o no existe appsettings.json. Omitiendo este paso."
          }

      - name: Iniciar Sesion en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y Subir Imagen Docker a Packages
        shell: bash
        run: |
          echo "Iniciando proceso de construccion y publicacion..."
          
          SERVICE_LOWER=$(echo "${{ inputs.service_name }}" | tr '[:upper:]' '[:lower:]')
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_ID="ghcr.io/$OWNER_LOWER/$SERVICE_LOWER"
          
          echo "Paso 1: Construyendo imagen localmente y capturando bitacora..."
          # El comando 'tee' permite ver el log en pantalla y al mismo tiempo guardarlo en un archivo txt
          docker build -t $IMAGE_ID:latest -f ${{ inputs.dockerfile_path }} ${{ inputs.context_path }} 2>&1 | tee bitacora_construccion.txt
          
          echo "Paso 2: Subiendo imagen a GitHub Packages (ghcr.io)"
          docker push $IMAGE_ID:latest
          
          echo "Operacion completada. La imagen esta disponible en el repositorio."

      - name: Guardar Bitacora de Construccion en Carpeta
        uses: actions/upload-artifact@v4
        with:
          name: Logs-Construccion-${{ inputs.service_name }}
          path: bitacora_construccion.txt
          retention-days: 5