CREATE TABLE IF NOT EXISTS cotizaciones (
    id VARCHAR(36) PRIMARY KEY,
    folio VARCHAR(20) UNIQUE NOT NULL,
    clienteId VARCHAR(50) NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    estado ENUM('BORRADOR', 'ENVIADA', 'ACEPTADA', 'RECHAZADA') DEFAULT 'BORRADOR',
    fechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fechaActualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);