@HostAddress = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxaUFMOEgyMURXU3F5Y1lyRVY4dEg1RzM0Mmd4M0EybmppVG05aVpVdHJ0RGxiMGZqTmRzc1ltMmJPTTB6anF1IiwiaWQiOiIzIiwicm9sIjoiVmVudGFzIiwiZXhwIjoxNzc4NjA3Nzk4LCJpc3MiOiJBbGZMYWJBcGkiLCJhdWQiOiJBbGZMYWJGcm9udGVuZCJ9.xBeNUb3Sb9rGR_VBX1acHRqB41ei2c1TAsbdykFUzuY",
  "refreshToken": "QeB8+xjClKWNzfcahbbYRFW06ftMbUNrD+ftKdV2xm7Q5GFgd4F6Xd+3aNwUaz9AjussRkSQpJtFF6W85YNz2w=="

### =========================================================
### PREPARACIÓN DE DATOS ANTES DE QUE LLEGUE EL MAESTRO
### =========================================================
# ⚠️ EJECUTA ESTO 3 O 4 VECES CAMBIANDO EL CLIENTE Y EL TOTAL 
# PARA LLENAR TU BASE DE DATOS DE DUMMYS.
POST {{HostAddress}}/api/cotizaciones
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clienteId": "EMP-991",
  "descripcion": "Cotización de Mantenimiento Inicial",
  "total": 15000,
  "productos": [
    { "nombre": "Mantenimiento Preventivo", "cantidad": 1, "precio": 15000 }
  ]
}

### =========================================================
### PASO 1 Y 4: CONSULTAR REPLICA (HAPPY PATH)
### =========================================================
# Demuestra que la réplica te devuelve los datos sincronizados.
GET {{HostAddress}}/api/cotizaciones
Authorization: Bearer {{token}}

### =========================================================
### PASO 2 Y 3: INSERTAR EN EL MAESTRO
### =========================================================
# Ejecuta esto para demostrar que el Maestro guarda datos 
# incluso si tiras el contenedor de la Réplica.
POST {{HostAddress}}/api/cotizaciones
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clienteId": "CL-NUEVO",
  "descripcion": "Cotización Urgente con Réplica Caída",
  "total": 8500,
  "productos": [
    { "nombre": "Servicio de Emergencia", "cantidad": 1, "precio": 8500 }
  ]
}

### =========================================================
### PASO 5.D: VULNERABILIDAD CMD INJECTION
### =========================================================
# Demuestra que el sistema sanitiza el ataque y no ejecuta 
# comandos a nivel de sistema operativo.
POST {{HostAddress}}/api/cotizaciones
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clienteId": "HACKER-01",
  "descripcion": "Intento de borrado de compilación",
  "total": 500,
  "productos": [
    { "nombre": "Reactivos; rm -rf /app/dist", "cantidad": 1, "precio": 500 }
  ]
}